#' Change the year of tax component data
#'
#' @description Calculating future tax bill requires future (unavailable) data.
#'   This function enables future calculations/simulations by copying past data
#'   into the future. It can be combined with other functions to simulate
#'   complex future scenarios.
#'
#' @param df A data frame in the format generated by
#'   \code{\link{lookup_agency_eavs}}, \code{\link{lookup_exemptions}},
#'    \code{\link{lookup_levies}}, or \code{\link{lookup_tifs}}. Must have a
#'    \code{year} column.
#' @param from_year Year to copy data from. Must be a length 1 numeric vector.
#' @param to_year Year to change copied data to. Must be a length
#'   1 numeric vector.
#'
#' @return Data frame of copied data with \code{year} updated to the value of
#'   \code{to_year}.
#'
#' @examples
#' library(magrittr)
#'
#' lookup_levies(2019, "73105") %>%
#'   change_year(from_year = 2019, to_year = 2020)
#' @md
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#' @family change
#' @export
change_year <- function(df, from_year, to_year) {
  stopifnot(
    is.data.frame(df),
    is.numeric(df$year),
    is.numeric(from_year),
    length(from_year) == 1,
    is.numeric(to_year),
    length(to_year) == 1,
    any(df$year %in% from_year)
  )

  out <- df %>%
    dplyr::filter(.data$year == from_year) %>%
    dplyr::mutate(year = to_year)

  return(out)
}


#' @describeIn change_year A helper function equivalent to
#'   \code{change_year(df, max_year, max_year + 1)}. Copies the latest year and
#'   adds 1 year.
#'
#' @export
change_year_copy_latest <- function(df) {
  stopifnot(
    is.data.frame(df),
    is.numeric(df$year)
  )

  max_year <- max(df$year)
  out <- change_year(df, max_year, max_year + 1)

  return(out)
}
