on:
  workflow_dispatch:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

name: pkgdown

jobs:
  build-pkgdown-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@a51a8012b0aab7c32ef9d19bf54da93f3254335e # v2.12.0

      - name: Setup R
        uses: r-lib/actions/setup-r@a51a8012b0aab7c32ef9d19bf54da93f3254335e # v2.12.0
        with:
          use-public-rspm: true

      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@a51a8012b0aab7c32ef9d19bf54da93f3254335e # v2.12.0
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Prepare PTAXSIM database
        id: prep_ptaxsim_db
        uses: ./.github/actions/prepare-ptaxsim

      - name: Set PTAXSIM database path
        run: echo "PTAXSIM_DB_PATH=${{ steps.prep_ptaxsim_db.outputs.PTAXSIM_DB_DIR }}/ptaxsim.db" >> $GITHUB_ENV
        shell: bash

      - name: Build pkgdown site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0

      - name: Install docs build dependencies
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Prepare Mermaid assets for docs
        run: |
          for file in inst/mermaid/*.mmd; do
            # Confine the mermaid process to an AppArmor profile, necessary on
            # Ubuntu >= 23.10 to work around new AppArmor rules that block the
            # Puppeteer sandbox (used by mermaid) from working. See:
            # https://github.com/mermaid-js/mermaid-cli/issues/730#issuecomment-2408615110
            aa-exec --profile=chrome mmdc -i "$file" -o "${file/.mmd/.svg}"
          done
          mkdir -p docs/mermaid
          mv inst/mermaid/*.svg docs/mermaid
        working-directory: ${{ env.PROJECT_DIR }}
        shell: bash

      - name: Configure pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: 'docs'

  deploy:
    if: contains(fromJSON('["main", "master"]'), github.ref_name) && github.event_name != 'pull_request'
    needs: build-pkgdown-site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
