on:
  pull_request:
  push:
    branches: [main, master]

name: pre-commit

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run pre-commit checks
        uses: ccao-data/actions/pre-commit@main
